---
# copy gitconfig file using ansible ad-hoc
# ansible -m copy -a "src=master.gitconfig dest=~/.gitconfig" localhost

- name: Ensure ~/.gitconfig is copied from master.gitconfig
  hosts: localhost
  tasks:
  - copy: src="../adhoc/master.gitconfig" dest="~/.gitconfig"

- name: Ensure homebrew packages are installed.
  hosts: localhost
  tasks:
  - community.general.homebrew: 
      name: jq
      state: latest
   